// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc2
// source: utils/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Seller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seller) Reset() {
	*x = Seller{}
	mi := &file_utils_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seller) ProtoMessage() {}

func (x *Seller) ProtoReflect() protoreflect.Message {
	mi := &file_utils_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seller.ProtoReflect.Descriptor instead.
func (*Seller) Descriptor() ([]byte, []int) {
	return file_utils_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *Seller) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Seller) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Seller) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Seller) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CheckSellerExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSellerExistsRequest) Reset() {
	*x = CheckSellerExistsRequest{}
	mi := &file_utils_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSellerExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSellerExistsRequest) ProtoMessage() {}

func (x *CheckSellerExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utils_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSellerExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckSellerExistsRequest) Descriptor() ([]byte, []int) {
	return file_utils_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *CheckSellerExistsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CheckSellerExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSellerExistsResponse) Reset() {
	*x = CheckSellerExistsResponse{}
	mi := &file_utils_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSellerExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSellerExistsResponse) ProtoMessage() {}

func (x *CheckSellerExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utils_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSellerExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckSellerExistsResponse) Descriptor() ([]byte, []int) {
	return file_utils_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *CheckSellerExistsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type GetUserDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsRequest) Reset() {
	*x = GetUserDetailsRequest{}
	mi := &file_utils_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsRequest) ProtoMessage() {}

func (x *GetUserDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utils_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetUserDetailsRequest) Descriptor() ([]byte, []int) {
	return file_utils_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserDetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsResponse) Reset() {
	*x = GetUserDetailsResponse{}
	mi := &file_utils_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsResponse) ProtoMessage() {}

func (x *GetUserDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utils_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDetailsResponse) Descriptor() ([]byte, []int) {
	return file_utils_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserDetailsResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserDetailsResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserDetailsResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetSellerDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerDetailsRequest) Reset() {
	*x = GetSellerDetailsRequest{}
	mi := &file_utils_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerDetailsRequest) ProtoMessage() {}

func (x *GetSellerDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utils_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetSellerDetailsRequest) Descriptor() ([]byte, []int) {
	return file_utils_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetSellerDetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSellerDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessName  string                 `protobuf:"bytes,1,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerDetailsResponse) Reset() {
	*x = GetSellerDetailsResponse{}
	mi := &file_utils_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerDetailsResponse) ProtoMessage() {}

func (x *GetSellerDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utils_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetSellerDetailsResponse) Descriptor() ([]byte, []int) {
	return file_utils_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetSellerDetailsResponse) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

var File_utils_user_user_proto protoreflect.FileDescriptor

const file_utils_user_user_proto_rawDesc = "" +
	"\n" +
	"\x15utils/user/user.proto\x12\tecommerce\"a\n" +
	"\x06Seller\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"*\n" +
	"\x18CheckSellerExistsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x19CheckSellerExistsResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"'\n" +
	"\x15GetUserDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"r\n" +
	"\x16GetUserDetailsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\")\n" +
	"\x17GetSellerDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x18GetSellerDetailsResponse\x12#\n" +
	"\rbusiness_name\x18\x01 \x01(\tR\fbusinessName2\x9a\x02\n" +
	"\x04User\x12^\n" +
	"\x11CheckSellerExists\x12#.ecommerce.CheckSellerExistsRequest\x1a$.ecommerce.CheckSellerExistsResponse\x12U\n" +
	"\x0eGetUserDetails\x12 .ecommerce.GetUserDetailsRequest\x1a!.ecommerce.GetUserDetailsResponse\x12[\n" +
	"\x10GetSellerDetails\x12\".ecommerce.GetSellerDetailsRequest\x1a#.ecommerce.GetSellerDetailsResponseB\rZ\v/utils/userb\x06proto3"

var (
	file_utils_user_user_proto_rawDescOnce sync.Once
	file_utils_user_user_proto_rawDescData []byte
)

func file_utils_user_user_proto_rawDescGZIP() []byte {
	file_utils_user_user_proto_rawDescOnce.Do(func() {
		file_utils_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utils_user_user_proto_rawDesc), len(file_utils_user_user_proto_rawDesc)))
	})
	return file_utils_user_user_proto_rawDescData
}

var file_utils_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_utils_user_user_proto_goTypes = []any{
	(*Seller)(nil),                    // 0: ecommerce.Seller
	(*CheckSellerExistsRequest)(nil),  // 1: ecommerce.CheckSellerExistsRequest
	(*CheckSellerExistsResponse)(nil), // 2: ecommerce.CheckSellerExistsResponse
	(*GetUserDetailsRequest)(nil),     // 3: ecommerce.GetUserDetailsRequest
	(*GetUserDetailsResponse)(nil),    // 4: ecommerce.GetUserDetailsResponse
	(*GetSellerDetailsRequest)(nil),   // 5: ecommerce.GetSellerDetailsRequest
	(*GetSellerDetailsResponse)(nil),  // 6: ecommerce.GetSellerDetailsResponse
}
var file_utils_user_user_proto_depIdxs = []int32{
	1, // 0: ecommerce.User.CheckSellerExists:input_type -> ecommerce.CheckSellerExistsRequest
	3, // 1: ecommerce.User.GetUserDetails:input_type -> ecommerce.GetUserDetailsRequest
	5, // 2: ecommerce.User.GetSellerDetails:input_type -> ecommerce.GetSellerDetailsRequest
	2, // 3: ecommerce.User.CheckSellerExists:output_type -> ecommerce.CheckSellerExistsResponse
	4, // 4: ecommerce.User.GetUserDetails:output_type -> ecommerce.GetUserDetailsResponse
	6, // 5: ecommerce.User.GetSellerDetails:output_type -> ecommerce.GetSellerDetailsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utils_user_user_proto_init() }
func file_utils_user_user_proto_init() {
	if File_utils_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utils_user_user_proto_rawDesc), len(file_utils_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utils_user_user_proto_goTypes,
		DependencyIndexes: file_utils_user_user_proto_depIdxs,
		MessageInfos:      file_utils_user_user_proto_msgTypes,
	}.Build()
	File_utils_user_user_proto = out.File
	file_utils_user_user_proto_goTypes = nil
	file_utils_user_user_proto_depIdxs = nil
}
