// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc2
// source: utils/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SellerId      int64                  `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailsResponse) Reset() {
	*x = GetProductDetailsResponse{}
	mi := &file_utils_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailsResponse) ProtoMessage() {}

func (x *GetProductDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utils_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetProductDetailsResponse) Descriptor() ([]byte, []int) {
	return file_utils_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductDetailsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductDetailsResponse) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *GetProductDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProductDetailsResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetProductDetailsResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type GetProductDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailsRequest) Reset() {
	*x = GetProductDetailsRequest{}
	mi := &file_utils_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailsRequest) ProtoMessage() {}

func (x *GetProductDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utils_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetProductDetailsRequest) Descriptor() ([]byte, []int) {
	return file_utils_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductDetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_utils_product_product_proto protoreflect.FileDescriptor

const file_utils_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1butils/product/product.proto\x12\aproduct\"\xaa\x01\n" +
	"\x19GetProductDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x03R\bsellerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\"*\n" +
	"\x18GetProductDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2e\n" +
	"\aProduct\x12Z\n" +
	"\x11GetProductDetails\x12!.product.GetProductDetailsRequest\x1a\".product.GetProductDetailsResponseB\x10Z\x0e/utils/productb\x06proto3"

var (
	file_utils_product_product_proto_rawDescOnce sync.Once
	file_utils_product_product_proto_rawDescData []byte
)

func file_utils_product_product_proto_rawDescGZIP() []byte {
	file_utils_product_product_proto_rawDescOnce.Do(func() {
		file_utils_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utils_product_product_proto_rawDesc), len(file_utils_product_product_proto_rawDesc)))
	})
	return file_utils_product_product_proto_rawDescData
}

var file_utils_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_utils_product_product_proto_goTypes = []any{
	(*GetProductDetailsResponse)(nil), // 0: product.GetProductDetailsResponse
	(*GetProductDetailsRequest)(nil),  // 1: product.GetProductDetailsRequest
}
var file_utils_product_product_proto_depIdxs = []int32{
	1, // 0: product.Product.GetProductDetails:input_type -> product.GetProductDetailsRequest
	0, // 1: product.Product.GetProductDetails:output_type -> product.GetProductDetailsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utils_product_product_proto_init() }
func file_utils_product_product_proto_init() {
	if File_utils_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utils_product_product_proto_rawDesc), len(file_utils_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utils_product_product_proto_goTypes,
		DependencyIndexes: file_utils_product_product_proto_depIdxs,
		MessageInfos:      file_utils_product_product_proto_msgTypes,
	}.Build()
	File_utils_product_product_proto = out.File
	file_utils_product_product_proto_goTypes = nil
	file_utils_product_product_proto_depIdxs = nil
}
